project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  - source: /**/language/en-GB/*.ini
    translation: /%original_path%/%locale%/%original_file_name%
    translation_replace:
      "en-GB/nl-NL": "nl-NL"

    
