project_id_env: 924715
api_token_env: 

preserve_hierarchy: true

files:
  - source: /**/language/en-GB/*.ini
    translation: /%original_path%/%locale%/%original_file_name%
    translation_replace:
      "en-GB/nl-NL": "nl-NL"
    
