CREATE TABLE IF NOT EXISTS `#__jem_events` (
    `id` int(11) unsigned NOT NULL auto_increment,
    `locid` int(11) unsigned NOT NULL DEFAULT '0',
    `dates` date NULL DEFAULT NULL,
    `enddates` date NULL DEFAULT NULL,
    `times` time NULL DEFAULT NULL,
    `endtimes` time NULL DEFAULT NULL,
    `timezone_mode` varchar(10) NOT NULL DEFAULT 'joomla',
    `timezone` varchar(64) NOT NULL DEFAULT '',
    `start_utc` datetime NULL DEFAULT NULL,
    `end_utc` datetime NULL DEFAULT NULL,
    `title` varchar(255) NOT NULL DEFAULT '',
    `alias` varchar(255) NOT NULL DEFAULT '',
    `created_by` int(11) unsigned NOT NULL DEFAULT '0',
    `modified` datetime NULL DEFAULT NULL,
    `modified_by` int(11) unsigned NOT NULL DEFAULT '0',
    `publish_up` datetime DEFAULT NULL,
    `publish_down` datetime DEFAULT NULL,
    `version` int(11) unsigned NOT NULL DEFAULT '0',
    `author_ip` varchar(80) DEFAULT NULL,
    `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `introtext` mediumtext NOT NULL,
    `fulltext` mediumtext NOT NULL,
    `article_id` int(10) unsigned NOT NULL DEFAULT '0',
    `online_meeting_url` varchar(2048) NOT NULL DEFAULT '',
    `online_meeting_label` varchar(255) NOT NULL DEFAULT '',
    `meta_keywords` varchar(200) DEFAULT NULL,
    `meta_description` varchar(255) DEFAULT NULL,
    `recurrence_first_id` int(11) NOT NULL DEFAULT '0',
    `recurrence_number` int(11) NOT NULL DEFAULT '0',
    `recurrence_type` int(2) NOT NULL DEFAULT '0',
    `recurrence_counter` int(11) NOT NULL DEFAULT '0',
    `recurrence_limit` int(11) NOT NULL DEFAULT '0',
    `recurrence_limit_date` date NULL DEFAULT NULL,
    `recurrence_byday` varchar(20) NULL DEFAULT NULL,
    `recurrence_bylastday` varchar(20) NULL DEFAULT NULL,
    `series_id` int(11) unsigned NULL DEFAULT NULL,
    `series_order` int(11) unsigned NOT NULL DEFAULT '0',
    `parent_event_id` int(11) unsigned NULL DEFAULT NULL,
    `event_tree_order` int(11) unsigned NOT NULL DEFAULT '0',
    `show_in_calendar` tinyint(1) unsigned NOT NULL DEFAULT '0',
    `datimage` varchar(100) NOT NULL DEFAULT '',
    `fullimage` varchar(100) NOT NULL DEFAULT '',
    `image_path` varchar(255) NOT NULL DEFAULT '',
    `fullimage_layout` varchar(20) NOT NULL DEFAULT 'global',
    `checked_out` int(11) UNSIGNED NULL DEFAULT NULL,
    `checked_out_time` datetime NULL DEFAULT NULL,
    `registra` tinyint(1) NOT NULL DEFAULT '0',
    `registra_from` datetime DEFAULT NULL,
    `registra_until` datetime DEFAULT NULL,
    `unregistra` tinyint(1) NOT NULL DEFAULT 0,
    `unregistra_until` datetime DEFAULT NULL,
    `reginvitedonly` INT(1) NOT NULL DEFAULT '0',
    `maxplaces` int(11) NOT NULL DEFAULT '0',
    `minbookeduser` int(11) NOT NULL DEFAULT 1,
    `maxbookeduser` int(11) NOT NULL DEFAULT 1,
    `reservedplaces`  int(11) NOT NULL DEFAULT 0,
    `waitinglist` tinyint(1) NOT NULL DEFAULT '0',
    `requestanswer` tinyint(1) NOT NULL DEFAULT '0',
    `seriesbooking` int(1) NOT NULL DEFAULT '0',
    `singlebooking` int(1) NOT NULL DEFAULT '0',
    `hits` int(11) unsigned NOT NULL DEFAULT '0',
    `last_visit` datetime NULL DEFAULT NULL,
    `published` tinyint(1) NOT NULL DEFAULT '0',
    `contactid` varchar(100) NOT NULL DEFAULT '',
    `custom1` varchar(200) NOT NULL DEFAULT '',
    `custom2` varchar(200) NOT NULL DEFAULT '',
    `custom3` varchar(100) NOT NULL DEFAULT '',
    `custom4` varchar(100) NOT NULL DEFAULT '',
    `custom5` varchar(100) NOT NULL DEFAULT '',
    `custom6` varchar(100) NOT NULL DEFAULT '',
    `custom7` varchar(100) NOT NULL DEFAULT '',
    `custom8` varchar(100) NOT NULL DEFAULT '',
    `custom9` varchar(100) NOT NULL DEFAULT '',
    `custom10` varchar(100) NOT NULL DEFAULT '',    
    `created_by_alias` varchar(255) NOT NULL,
    `access` int(10) UNSIGNED NOT NULL DEFAULT '1',
    `metadata` text NOT NULL,
    `featured` tinyint(3) unsigned NOT NULL DEFAULT '0',
    `attribs` varchar(5120) NOT NULL DEFAULT '',
    `language` char(7) NOT NULL DEFAULT '*',
    `event_status` varchar(30) NOT NULL DEFAULT 'scheduled',
    `ticket_availability` varchar(30) NOT NULL DEFAULT 'instock',
    `type_id` int(11) unsigned NULL DEFAULT NULL,
    `venue_allocation_mode` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'none',
    `capacity_mode` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'classic',
    `pricing_mode` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'classic',
    `pricing_revision` int(10) unsigned NOT NULL DEFAULT '1',
    `currency` char(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
    `default_tax_rate_id` int(11) unsigned NULL DEFAULT NULL,
    `prices_include_tax` tinyint(1) NOT NULL DEFAULT '1',
    `management_fee_mode` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'fixed_per_ticket',
    `management_fee_value` decimal(15,2) NOT NULL DEFAULT '0.00',
    `management_fee_basis` varchar(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'gross',
    `management_fee_tax_rate_id` int(11) unsigned NULL DEFAULT NULL,
    `management_fee_refundable` tinyint(1) NOT NULL DEFAULT '0',
    `venue_profile_id` int(11) unsigned NULL DEFAULT NULL,
    `venue_profile_revision` int(10) unsigned NOT NULL DEFAULT '0',
    `venue_snapshot` mediumtext NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_venue` (`locid`),
    KEY `idx_access` (`access`),
    KEY `idx_checkout` (`checked_out`),
    KEY `idx_pubstate` (`published`),
    KEY `idx_createdby` (`created_by`),
    KEY `idx_language` (`language`),
    KEY `idx_article` (`article_id`),
    KEY `idx_type` (`type_id`),
    KEY `idx_start_utc` (`start_utc`),
    KEY `idx_end_utc` (`end_utc`),
    KEY `idx_series` (`series_id`, `series_order`),
    KEY `idx_venue_profile` (`venue_profile_id`, `venue_profile_revision`),
    KEY `idx_parent_event` (`parent_event_id`, `event_tree_order`),
    KEY `idx_event_calendar_tree` (`show_in_calendar`, `parent_event_id`)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_event_series` (
    `id` int(11) unsigned NOT NULL auto_increment,
    `root_event_id` int(11) unsigned NOT NULL DEFAULT '0',
    `title` varchar(255) NOT NULL DEFAULT '',
    `series_type` varchar(20) NOT NULL DEFAULT 'custom',
    `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_by` int(11) unsigned NOT NULL DEFAULT '0',
    `modified` datetime NULL DEFAULT NULL,
    `modified_by` int(11) unsigned NOT NULL DEFAULT '0',
    `published` tinyint(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (`id`),
    KEY `idx_root_event` (`root_event_id`),
    KEY `idx_created_by` (`created_by`),
    KEY `idx_published` (`published`)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_tax_rates` (
    `id` int(11) unsigned NOT NULL auto_increment,
    `code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `name` varchar(255) NOT NULL DEFAULT '',
    `tax_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `rate` decimal(7,2) NOT NULL DEFAULT '0.00',
    `country_code` char(2) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
    `region_code` varchar(100) NOT NULL DEFAULT '',
    `description` text DEFAULT NULL,
    `valid_from` date NULL DEFAULT NULL,
    `valid_until` date NULL DEFAULT NULL,
    `published` tinyint(1) NOT NULL DEFAULT '1',
    `ordering` int(11) NOT NULL DEFAULT '0',
    `checked_out` int(11) unsigned NULL DEFAULT NULL,
    `checked_out_time` datetime NULL DEFAULT NULL,
    `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_by` int(11) unsigned NOT NULL DEFAULT '0',
    `modified` datetime NULL DEFAULT NULL,
    `modified_by` int(11) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_tax_rate_code` (`code`),
    KEY `idx_tax_rate_published_ordering` (`published`, `ordering`),
    KEY `idx_tax_rate_country` (`country_code`, `published`, `valid_from`, `valid_until`),
    KEY `idx_tax_rate_validity` (`valid_from`, `valid_until`)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_capacity_pools` (
    `id` int(11) unsigned NOT NULL auto_increment,
    `event_id` int(11) unsigned NOT NULL,
    `venue_capacity_area_id` int(11) unsigned NULL DEFAULT NULL,
    `venue_layout_id` int(11) unsigned NULL DEFAULT NULL,
    `venue_layout_revision` int(10) unsigned NOT NULL DEFAULT '0',
    `allocation_mode` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'quantity',
    `code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `name` varchar(255) NOT NULL DEFAULT '',
    `description` text DEFAULT NULL,
    `capacity` int(10) unsigned NOT NULL DEFAULT '0',
    `published` tinyint(1) NOT NULL DEFAULT '1',
    `ordering` int(11) NOT NULL DEFAULT '0',
    `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_by` int(11) unsigned NOT NULL DEFAULT '0',
    `modified` datetime NULL DEFAULT NULL,
    `modified_by` int(11) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_capacity_pool_event_code` (`event_id`, `code`),
    KEY `idx_capacity_pool_event_published` (`event_id`, `published`, `ordering`),
    KEY `idx_capacity_pool_venue_area` (`venue_capacity_area_id`)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_event_prices` (
    `id` int(11) unsigned NOT NULL auto_increment,
    `event_id` int(11) unsigned NOT NULL,
    `capacity_pool_id` int(11) unsigned NULL DEFAULT NULL,
    `code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `name` varchar(255) NOT NULL DEFAULT '',
    `description` text DEFAULT NULL,
    `amount` decimal(15,2) NOT NULL DEFAULT '0.00',
    `tax_rate_id` int(11) unsigned NULL DEFAULT NULL,
    `quota` int(10) unsigned NULL DEFAULT NULL,
    `min_quantity` int(10) unsigned NOT NULL DEFAULT '1',
    `max_quantity` int(10) unsigned NULL DEFAULT NULL,
    `available_from` datetime NULL DEFAULT NULL,
    `available_until` datetime NULL DEFAULT NULL,
    `min_age` tinyint(3) unsigned NULL DEFAULT NULL,
    `max_age` tinyint(3) unsigned NULL DEFAULT NULL,
    `access_level_id` int(10) unsigned NULL DEFAULT '1',
    `user_group_id` int(10) unsigned NULL DEFAULT NULL,
    `verification_mode` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'none',
    `published` tinyint(1) NOT NULL DEFAULT '1',
    `ordering` int(11) NOT NULL DEFAULT '0',
    `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_by` int(11) unsigned NOT NULL DEFAULT '0',
    `modified` datetime NULL DEFAULT NULL,
    `modified_by` int(11) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_event_price_event_code` (`event_id`, `code`),
    KEY `idx_event_price_event_published` (`event_id`, `published`, `ordering`),
    KEY `idx_event_price_pool` (`capacity_pool_id`),
    KEY `idx_event_price_tax` (`tax_rate_id`),
    KEY `idx_event_price_availability` (`available_from`, `available_until`)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_venues` (
    `id` int(11) unsigned NOT NULL auto_increment,
    `venue` varchar(100) NOT NULL DEFAULT '',
    `alias` varchar(100) NOT NULL DEFAULT '',
    `color` varchar(7) NOT NULL DEFAULT '',
    `url` varchar(200)  NOT NULL DEFAULT '',
    `street` varchar(50) DEFAULT NULL,
    `postalCode` varchar(20) DEFAULT NULL,
    `city` varchar(50) DEFAULT NULL,
    `district` varchar(100) NOT NULL DEFAULT '',
    `level` varchar(100) NOT NULL DEFAULT '',
    `capacity` int(10) unsigned NOT NULL DEFAULT '0',
    `state` varchar(50) DEFAULT NULL,
    `country` varchar(2) DEFAULT NULL,
    `timezone` varchar(64) NOT NULL DEFAULT '',
    `email` varchar(254) NOT NULL DEFAULT '',
    `phone` varchar(50) NOT NULL DEFAULT '',
    `mobile` varchar(50) NOT NULL DEFAULT '',
    `latitude` decimal(10,6) DEFAULT NULL,
    `longitude` decimal(10,6) DEFAULT NULL,
    `locdescription` mediumtext DEFAULT NULL,
    `meta_keywords` text DEFAULT NULL,
    `meta_description` text DEFAULT NULL,
    `locimage` varchar(100) NOT NULL DEFAULT '',
    `image_path` varchar(255) NOT NULL DEFAULT '',
    `locimage_alt` varchar(255) NOT NULL DEFAULT '',
    `map` tinyint(4) NOT NULL DEFAULT '0',
    `created_by` int(11) unsigned NOT NULL DEFAULT '0',
    `author_ip` varchar(80) NOT NULL DEFAULT '',
    `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` datetime NULL DEFAULT NULL,
    `modified_by` int(11) unsigned NOT NULL DEFAULT '0',
    `version` int(11) unsigned NOT NULL DEFAULT '0',
    `published` tinyint(1) NOT NULL DEFAULT '0',
    `checked_out` int(11) UNSIGNED NULL DEFAULT NULL,
    `checked_out_time` datetime NULL DEFAULT NULL,
    `ordering` int(11) NOT NULL DEFAULT '0',
    `publish_up` datetime NULL DEFAULT NULL,
    `publish_down` datetime NULL DEFAULT NULL,
    `access` int(10) UNSIGNED NOT NULL DEFAULT '1',
    `custom1` varchar(200) NOT NULL DEFAULT '',
    `custom2` varchar(200) NOT NULL DEFAULT '',
    `custom3` varchar(100) NOT NULL DEFAULT '',
    `custom4` varchar(100) NOT NULL DEFAULT '',
    `custom5` varchar(100) NOT NULL DEFAULT '',
    `custom6` varchar(100) NOT NULL DEFAULT '',
    `custom7` varchar(100) NOT NULL DEFAULT '',
    `custom8` varchar(100) NOT NULL DEFAULT '',
    `custom9` varchar(100) NOT NULL DEFAULT '',
    `custom10` varchar(100) NOT NULL DEFAULT '',
    `attribs` varchar(5120) DEFAULT NULL,
    `language` char(7) NOT NULL DEFAULT '*',
    `type_id` int(11) unsigned NULL DEFAULT NULL,
    `parent_venue_id` int(11) unsigned NULL DEFAULT NULL,
    `venue_tree_order` int(11) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    KEY `idx_access` (`access`),
    KEY `idx_checkout` (`checked_out`),
    KEY `idx_pubstate` (`published`),
    KEY `idx_createdby` (`created_by`),
    KEY `idx_language` (`language`),
    KEY `idx_type` (`type_id`),
    KEY `idx_parent_venue` (`parent_venue_id`, `venue_tree_order`)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_venue_capacity_profiles` (
    `id` int(11) unsigned NOT NULL auto_increment,
    `venue_id` int(11) unsigned NOT NULL,
    `code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `name` varchar(255) NOT NULL DEFAULT '',
    `image` varchar(100) NOT NULL DEFAULT '',
    `image_alt` varchar(255) NOT NULL DEFAULT '',
    `revision` int(10) unsigned NOT NULL DEFAULT '1',
    `capacity` int(10) unsigned NOT NULL DEFAULT '0',
    `is_default` tinyint(1) NOT NULL DEFAULT '1',
    `published` tinyint(1) NOT NULL DEFAULT '1',
    `ordering` int(11) NOT NULL DEFAULT '0',
    `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_by` int(11) unsigned NOT NULL DEFAULT '0',
    `modified` datetime NULL DEFAULT NULL,
    `modified_by` int(11) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_venue_capacity_profile_code` (`venue_id`, `code`),
    KEY `idx_venue_capacity_profile_default` (`venue_id`, `is_default`, `published`, `ordering`)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_venue_spaces` (
    `id` int(11) unsigned NOT NULL auto_increment,
    `venue_id` int(11) unsigned NOT NULL,
    `code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `name` varchar(255) NOT NULL DEFAULT '',
    `image` varchar(100) NOT NULL DEFAULT '',
    `image_alt` varchar(255) NOT NULL DEFAULT '',
    `color` char(7) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '#2F6F9F',
    `description` text DEFAULT NULL,
    `published` tinyint(1) NOT NULL DEFAULT '1',
    `ordering` int(11) NOT NULL DEFAULT '0',
    `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_by` int(11) unsigned NOT NULL DEFAULT '0',
    `modified` datetime NULL DEFAULT NULL,
    `modified_by` int(11) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_venue_space_code` (`venue_id`, `code`),
    KEY `idx_venue_space_published` (`venue_id`, `published`, `ordering`)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_venue_layouts` (
    `id` int(11) unsigned NOT NULL auto_increment,
    `venue_space_id` int(11) unsigned NOT NULL,
    `code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `name` varchar(255) NOT NULL DEFAULT '',
    `image` varchar(100) NOT NULL DEFAULT '',
    `image_alt` varchar(255) NOT NULL DEFAULT '',
    `color` char(7) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '#B78324',
    `revision` int(10) unsigned NOT NULL DEFAULT '1',
    `capacity` int(10) unsigned NOT NULL DEFAULT '0',
    `published` tinyint(1) NOT NULL DEFAULT '1',
    `ordering` int(11) NOT NULL DEFAULT '0',
    `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_by` int(11) unsigned NOT NULL DEFAULT '0',
    `modified` datetime NULL DEFAULT NULL,
    `modified_by` int(11) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_venue_layout_revision` (`venue_space_id`, `code`, `revision`),
    KEY `idx_venue_layout_published` (`venue_space_id`, `published`, `ordering`)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_venue_profile_spaces` (
    `id` int(11) unsigned NOT NULL auto_increment,
    `venue_profile_id` int(11) unsigned NOT NULL,
    `venue_space_id` int(11) unsigned NOT NULL,
    `venue_layout_id` int(11) unsigned NOT NULL,
    `ordering` int(11) NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_venue_profile_space` (`venue_profile_id`, `venue_space_id`),
    KEY `idx_venue_profile_layout` (`venue_layout_id`)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_event_space_layouts` (
    `id` int(11) unsigned NOT NULL auto_increment,
    `event_id` int(11) unsigned NOT NULL,
    `venue_profile_id` int(11) unsigned NOT NULL,
    `venue_profile_revision` int(10) unsigned NOT NULL DEFAULT '0',
    `venue_profile_space_id` int(11) unsigned NULL DEFAULT NULL,
    `venue_space_id` int(11) unsigned NOT NULL,
    `venue_layout_id` int(11) unsigned NOT NULL,
    `venue_layout_revision` int(10) unsigned NOT NULL DEFAULT '0',
    `ordering` int(11) NOT NULL DEFAULT '0',
    `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_by` int(11) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_event_space_layout_assignment` (`event_id`, `venue_space_id`),
    KEY `idx_event_space_layout_profile_space` (`venue_profile_space_id`),
    KEY `idx_event_space_layout_profile` (`venue_profile_id`, `venue_profile_revision`),
    KEY `idx_event_space_layout_layout` (`venue_layout_id`, `venue_layout_revision`)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_space_conflict_overrides` (
    `id` bigint(20) unsigned NOT NULL auto_increment,
    `event_id` int(11) unsigned NOT NULL,
    `conflicting_event_id` int(11) unsigned NOT NULL,
    `venue_space_id` int(11) unsigned NOT NULL,
    `requested_start_utc` datetime NOT NULL,
    `requested_end_utc` datetime NOT NULL,
    `conflicting_start_utc` datetime NOT NULL,
    `conflicting_end_utc` datetime NOT NULL,
    `reason` varchar(1000) NOT NULL DEFAULT '',
    `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_by` int(11) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    KEY `idx_space_conflict_event` (`event_id`, `created`),
    KEY `idx_space_conflict_other_event` (`conflicting_event_id`),
    KEY `idx_space_conflict_space` (`venue_space_id`, `requested_start_utc`, `requested_end_utc`)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_venue_capacity_areas` (
    `id` int(11) unsigned NOT NULL auto_increment,
    `venue_layout_id` int(11) unsigned NOT NULL,
    `code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `name` varchar(255) NOT NULL DEFAULT '',
    `image` varchar(100) NOT NULL DEFAULT '',
    `image_alt` varchar(255) NOT NULL DEFAULT '',
    `color` char(7) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '#8A6D3B',
    `description` text DEFAULT NULL,
    `capacity` int(10) unsigned NOT NULL DEFAULT '0',
    `allocation_mode` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'quantity',
    `published` tinyint(1) NOT NULL DEFAULT '1',
    `ordering` int(11) NOT NULL DEFAULT '0',
    `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_by` int(11) unsigned NOT NULL DEFAULT '0',
    `modified` datetime NULL DEFAULT NULL,
    `modified_by` int(11) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_venue_capacity_area_code` (`venue_layout_id`, `code`),
    KEY `idx_venue_capacity_area_published` (`venue_layout_id`, `published`, `ordering`)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_categories` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `parent_id` int(11) unsigned NOT NULL DEFAULT '0',
    `catname` varchar(100) NOT NULL DEFAULT '',
    `alias` varchar(100) NOT NULL DEFAULT '',
    `description` mediumtext DEFAULT NULL,
    `meta_keywords` text DEFAULT NULL,
    `meta_description` text DEFAULT NULL,
    `image` varchar(100) NOT NULL DEFAULT '',
    `color` varchar(20) NOT NULL DEFAULT '',
    `published` tinyint(1) NOT NULL DEFAULT '0',
    `checked_out` int(11) UNSIGNED NULL DEFAULT NULL,
    `checked_out_time` datetime NULL DEFAULT NULL,
    `access` int(11) unsigned NOT NULL DEFAULT '1',
    `groupid` int(11) NOT NULL DEFAULT '0',
    `ordering` int(11) NOT NULL DEFAULT '0',
    `title` varchar(255) NOT NULL,
    `note` varchar(255) DEFAULT NULL,
    `lft` int(11) NOT NULL DEFAULT '0',
    `rgt` int(11) NOT NULL DEFAULT '0',
    `level` int(10) unsigned NOT NULL DEFAULT '1',
    `language` varchar(7) NOT NULL DEFAULT '*',
    `created_user_id` int(10) unsigned NOT NULL DEFAULT '0',
    `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `path` varchar(255) DEFAULT NULL,
    `metadata` varchar(2048) DEFAULT NULL,
    `modified_time` datetime NULL DEFAULT NULL,
    `modified_user_id` int(10) unsigned NOT NULL DEFAULT '0',
    `type_id` int(11) unsigned NULL DEFAULT NULL,
    `article_category_id` int(10) unsigned NOT NULL DEFAULT '0',
    `article_create_mode` tinyint(1) NOT NULL DEFAULT '0',
    `email` varchar(200) DEFAULT NULL,
    `emailacljl` tinyint(4) NOT NULL DEFAULT 0,
    `image_as_default` tinyint(1) NOT NULL DEFAULT '0',
    `event_image_default_storage` varchar(20) NOT NULL DEFAULT 'shared_root',
    PRIMARY KEY (`id`),
    KEY `idx_article_category` (`article_category_id`),
    KEY `idx_parent` (`parent_id`),
    KEY `idx_type` (`type_id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_cats_event_relations` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `catid` int(11) NOT NULL DEFAULT '0',
    `itemid` int(11) NOT NULL DEFAULT '0',
    `ordering` tinyint(11) NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `category event relation` (`catid`,`itemid`),
    KEY `catid` (`catid`),
    KEY `itemid` (`itemid`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_register` (
    `id` int(11) unsigned NOT NULL auto_increment,
    `event` int(11) NOT NULL DEFAULT '0',
    `uid` int(11) NOT NULL DEFAULT '0',
    `places` int(11) NOT NULL DEFAULT '1',
    `uregdate` varchar(50) NOT NULL DEFAULT '',
    `uip` varchar(45) NOT NULL DEFAULT '',
    `waiting` tinyint(1) NOT NULL DEFAULT '0',
    `status` tinyint(3) NOT NULL DEFAULT '1',
    `comment` varchar(255) DEFAULT '',
    `reference` varchar(28) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `created` datetime NULL DEFAULT NULL,
    `modified` datetime NULL DEFAULT NULL,
    `revision` int(10) unsigned NOT NULL DEFAULT '1',
    `pricing_mode` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'classic',
    `currency` char(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
    `subtotal_net` decimal(15,2) NULL DEFAULT NULL,
    `discount_total` decimal(15,2) NULL DEFAULT NULL,
    `tax_total` decimal(15,2) NULL DEFAULT NULL,
    `management_fee_net` decimal(15,2) NULL DEFAULT NULL,
    `management_fee_tax` decimal(15,2) NULL DEFAULT NULL,
    `management_fee_gross` decimal(15,2) NULL DEFAULT NULL,
    `grand_total` decimal(15,2) NULL DEFAULT NULL,
    `payment_state` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NULL DEFAULT NULL,
    `price_locked_at` datetime NULL DEFAULT NULL,
    `external_payment_reference` varchar(255) NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_user_event` (`uid`,`event`),
    UNIQUE KEY `idx_register_reference` (`reference`),
    KEY `idx_event` (`event`),
    KEY `idx_event_status` (`event`,`status`),
    KEY `idx_user` (`uid`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_register_items` (
    `id` bigint(20) unsigned NOT NULL auto_increment,
    `register_id` int(11) unsigned NOT NULL,
    `registration_revision` int(10) unsigned NOT NULL,
    `line_number` int(10) unsigned NOT NULL,
    `line_kind` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `event_price_id` int(11) unsigned NULL DEFAULT NULL,
    `capacity_pool_id` int(11) unsigned NULL DEFAULT NULL,
    `item_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
    `item_name` varchar(255) NOT NULL DEFAULT '',
    `item_description` text DEFAULT NULL,
    `quantity` int(10) unsigned NOT NULL DEFAULT '1',
    `currency` char(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `price_includes_tax` tinyint(1) NOT NULL DEFAULT '1',
    `unit_net` decimal(15,2) NOT NULL DEFAULT '0.00',
    `unit_tax` decimal(15,2) NOT NULL DEFAULT '0.00',
    `unit_gross` decimal(15,2) NOT NULL DEFAULT '0.00',
    `line_net` decimal(15,2) NOT NULL DEFAULT '0.00',
    `line_tax` decimal(15,2) NOT NULL DEFAULT '0.00',
    `line_gross` decimal(15,2) NOT NULL DEFAULT '0.00',
    `tax_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
    `tax_name` varchar(255) NOT NULL DEFAULT '',
    `tax_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
    `tax_rate` decimal(7,2) NOT NULL DEFAULT '0.00',
    `calculation_mode` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
    `calculation_value` decimal(15,2) NULL DEFAULT NULL,
    `calculation_basis` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
    `condition_snapshot` mediumtext DEFAULT NULL,
    `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_register_item_revision_line` (`register_id`, `registration_revision`, `line_number`),
    KEY `idx_register_item_price` (`event_price_id`),
    KEY `idx_register_item_pool` (`capacity_pool_id`),
    KEY `idx_register_item_kind` (`line_kind`)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_register_capacity_allocations` (
    `id` bigint(20) unsigned NOT NULL auto_increment,
    `register_id` int(11) unsigned NOT NULL,
    `registration_revision` int(10) unsigned NOT NULL,
    `event_id` int(11) unsigned NOT NULL,
    `venue_capacity_area_id` int(11) unsigned NULL DEFAULT NULL,
    `venue_layout_id` int(11) unsigned NOT NULL,
    `venue_layout_revision` int(10) unsigned NOT NULL DEFAULT '0',
    `area_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
    `area_name` varchar(255) NOT NULL DEFAULT '',
    `space_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
    `space_name` varchar(255) NOT NULL DEFAULT '',
    `quantity` int(10) unsigned NOT NULL DEFAULT '0',
    `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_register_capacity_revision_area` (`register_id`, `registration_revision`, `venue_layout_id`, `area_code`),
    KEY `idx_register_capacity_event_area` (`event_id`, `venue_capacity_area_id`),
    KEY `idx_register_capacity_event_layout` (`event_id`, `venue_layout_id`)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_register_history` (
    `id` bigint(20) unsigned NOT NULL auto_increment,
    `operation_reference` varchar(28) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `registration_id` int(11) unsigned NOT NULL,
    `registration_reference` varchar(28) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `revision` int(10) unsigned NOT NULL,
    `event_id` int(11) unsigned NOT NULL DEFAULT '0',
    `event_title` varchar(255) NOT NULL DEFAULT '',
    `action` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `old_status` tinyint(3) NULL DEFAULT NULL,
    `new_status` tinyint(3) NULL DEFAULT NULL,
    `old_places` int(11) NULL DEFAULT NULL,
    `new_places` int(11) NULL DEFAULT NULL,
    `old_user_id` int(11) NULL DEFAULT NULL,
    `new_user_id` int(11) NULL DEFAULT NULL,
    `actor_user_id` int(11) unsigned NOT NULL DEFAULT '0',
    `source` varchar(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
    `reason_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NULL DEFAULT NULL,
    `forced` tinyint(1) NOT NULL DEFAULT '0',
    `changed_fields` text NULL DEFAULT NULL,
    `occurred` datetime NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_history_registration_revision` (`registration_id`,`revision`),
    UNIQUE KEY `idx_history_operation_registration` (`operation_reference`,`registration_id`),
    KEY `idx_history_reference_occurred` (`registration_reference`,`occurred`),
    KEY `idx_history_operation` (`operation_reference`),
    KEY `idx_history_event_occurred` (`event_id`,`occurred`),
    KEY `idx_history_actor_occurred` (`actor_user_id`,`occurred`),
    KEY `idx_history_action_occurred` (`action`,`occurred`),
    KEY `idx_history_source_occurred` (`source`,`occurred`),
    KEY `idx_history_status_occurred` (`new_status`,`occurred`),
    KEY `idx_history_occurred` (`occurred`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_notifications` (
    `id` bigint(20) unsigned NOT NULL auto_increment,
    `notification_uuid` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `registration_id` int(11) unsigned NOT NULL DEFAULT '0',
    `registration_reference` varchar(28) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
    `registration_revision` int(10) unsigned NOT NULL DEFAULT '0',
    `event_id` int(11) unsigned NOT NULL DEFAULT '0',
    `reminder_definition_id` int(11) unsigned NULL DEFAULT NULL,
    `ticket_id` bigint(20) unsigned NULL DEFAULT NULL COMMENT 'Reserved for a future individual ticket/QR phase',
    `notification_type` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `recipient_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'user',
    `recipient_user_id` int(11) unsigned NOT NULL DEFAULT '0',
    `recipient_name` varchar(255) NOT NULL DEFAULT '',
    `recipient_email` varchar(320) NOT NULL,
    `requested_language` varchar(12) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
    `resolved_language` varchar(12) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'en-GB',
    `language_source` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'fallback',
    `fallback_reason` varchar(255) NOT NULL DEFAULT '',
    `template_id` varchar(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
    `subject` text NOT NULL,
    `body` mediumtext NOT NULL,
    `htmlbody` mediumtext NULL DEFAULT NULL,
    `payload_json` mediumtext NULL DEFAULT NULL,
    `attachments_json` mediumtext NULL DEFAULT NULL COMMENT 'Reserved for a future individual ticket/PDF phase',
    `content_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `state` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'queued',
    `scheduled_at` datetime NULL DEFAULT NULL,
    `queued_at` datetime NULL DEFAULT NULL,
    `processing_started_at` datetime NULL DEFAULT NULL,
    `sent_at` datetime NULL DEFAULT NULL,
    `failed_at` datetime NULL DEFAULT NULL,
    `cancelled_at` datetime NULL DEFAULT NULL,
    `next_attempt_at` datetime NULL DEFAULT NULL,
    `attempt_count` int(10) unsigned NOT NULL DEFAULT '0',
    `max_attempts` int(10) unsigned NOT NULL DEFAULT '4',
    `idempotency_key` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `resend_of` bigint(20) unsigned NULL DEFAULT NULL,
    `source` varchar(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
    `created_by` int(11) unsigned NOT NULL DEFAULT '0',
    `created` datetime NOT NULL,
    `modified` datetime NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_notification_uuid` (`notification_uuid`),
    UNIQUE KEY `idx_notification_idempotency` (`idempotency_key`),
    KEY `idx_notification_registration_created` (`registration_id`,`created`),
    KEY `idx_notification_reference_created` (`registration_reference`,`created`),
    KEY `idx_notification_event_created` (`event_id`,`created`),
    KEY `idx_notification_reminder_schedule` (`reminder_definition_id`,`scheduled_at`),
    KEY `idx_notification_recipient_created` (`recipient_user_id`,`created`),
    KEY `idx_notification_email_created` (`recipient_email`(191),`created`),
    KEY `idx_notification_state_attempt` (`state`,`next_attempt_at`),
    KEY `idx_notification_resend_of` (`resend_of`),
    KEY `idx_notification_created` (`created`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_reminders` (
    `id` int(11) unsigned NOT NULL auto_increment,
    `event_id` int(11) unsigned NOT NULL DEFAULT '0',
    `source_id` int(11) unsigned NULL DEFAULT NULL,
    `code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `title` varchar(255) NOT NULL DEFAULT '',
    `minutes` int(10) unsigned NOT NULL DEFAULT '1440',
    `published` tinyint(1) NOT NULL DEFAULT '1',
    `default_new_event` tinyint(1) NOT NULL DEFAULT '0',
    `ordering` int(11) NOT NULL DEFAULT '0',
    `created` datetime NOT NULL,
    `modified` datetime NOT NULL,
    `created_by` int(11) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_reminder_event_code` (`event_id`,`code`),
    KEY `idx_reminder_event_published_ordering` (`event_id`,`published`,`ordering`),
    UNIQUE KEY `idx_reminder_source_event` (`source_id`,`event_id`)
) ENGINE=InnoDB;

INSERT IGNORE INTO `#__jem_reminders` (`event_id`, `source_id`, `code`, `title`, `minutes`, `published`, `default_new_event`, `ordering`, `created`, `modified`, `created_by`) VALUES
(0, NULL, 'default_7_days', 'COM_JEM_REMINDER_DEFAULT_7_DAYS', 10080, 1, 1, 1, UTC_TIMESTAMP(), UTC_TIMESTAMP(), 0),
(0, NULL, 'default_24_hours', 'COM_JEM_REMINDER_DEFAULT_24_HOURS', 1440, 1, 1, 2, UTC_TIMESTAMP(), UTC_TIMESTAMP(), 0),
(0, NULL, 'default_2_hours', 'COM_JEM_REMINDER_DEFAULT_2_HOURS', 120, 1, 1, 3, UTC_TIMESTAMP(), UTC_TIMESTAMP(), 0);

CREATE TABLE IF NOT EXISTS `#__jem_notifications_attempts` (
    `id` bigint(20) unsigned NOT NULL auto_increment,
    `notification_id` bigint(20) unsigned NOT NULL,
    `attempt_number` int(10) unsigned NOT NULL,
    `transport` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'mail',
    `source` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'automatic',
    `requested_by_user_id` int(11) unsigned NOT NULL DEFAULT '0',
    `started_at` datetime NOT NULL,
    `finished_at` datetime NULL DEFAULT NULL,
    `result` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'processing',
    `transport_message_id` varchar(255) NOT NULL DEFAULT '',
    `error_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
    `error_message` varchar(1000) NOT NULL DEFAULT '',
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_attempt_notification_number` (`notification_id`,`attempt_number`),
    KEY `idx_attempt_notification_started` (`notification_id`,`started_at`),
    KEY `idx_attempt_result_started` (`result`,`started_at`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_groups` (
    `id` int(11) unsigned NOT NULL auto_increment,
    `name` varchar(150) NOT NULL DEFAULT '',
    `description` mediumtext DEFAULT NULL,
    `published` tinyint(1) NOT NULL DEFAULT '1',
    `checked_out` int(11) UNSIGNED NULL DEFAULT NULL,
    `checked_out_time` datetime NULL DEFAULT NULL,
    `addvenue` int(11) NOT NULL,
    `addevent` int(11) NOT NULL,
    `publishvenue` int(11) NOT NULL,
    `editvenue` int(11) NOT NULL,
    `publishevent` int(11) NOT NULL,
    `editevent` int(11) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_groupmembers` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `group_id` int(11) NOT NULL DEFAULT '0',
    `member` int(11) NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    KEY `idx_group` (`group_id`),
    KEY `idx_user` (`member`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_config` (
    `keyname` varchar(100) NOT NULL,
    `value` text,
    `access` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'rfu',
    PRIMARY KEY (`keyname`),
    KEY `idx_access` (`access`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_attachments` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `object` varchar(255) NOT NULL,
    `file` varchar(255) NOT NULL,
    `name` varchar(255) DEFAULT NULL,
    `description` varchar(255) DEFAULT NULL,
    `icon` varchar(255) DEFAULT NULL,
    `frontend` tinyint(1) NOT NULL DEFAULT '1',
    `access` int(10) UNSIGNED NOT NULL DEFAULT '1',
    `ordering` int(11) NOT NULL DEFAULT '0',
    `created` datetime NULL DEFAULT NULL,
    `created_by` int(11) NOT NULL DEFAULT '0',
    `downloads` int(11) unsigned NOT NULL DEFAULT '0',
    `last_download` datetime NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_countries` (
    `id` int(11) unsigned NOT NULL auto_increment,
    `continent` varchar(2) NOT NULL,
    `iso2` varchar(2) NOT NULL,
    `iso3` varchar(3) NOT NULL,
    `un` int(11) NOT NULL,
    `name` varchar(100) NOT NULL,
    `currency` char(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
    `published` tinyint(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (`id`),
    KEY `iso2` (`iso2`),
    KEY `idx_continent` (`continent`),
    KEY `idx_published` (`published`)
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS `#__jem_links` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `event_id` INT(11) NOT NULL,
    `type` VARCHAR(50) NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `description` VARCHAR(255) NULL,
    `url` TEXT NOT NULL,
    `params` TEXT DEFAULT NULL,
    `ordering` INT(11) DEFAULT 0,
    `state` TINYINT(1) DEFAULT 1,
    `created` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `created_by` INT(11) NOT NULL,
    `modified` DATETIME DEFAULT NULL,
    `modified_by` INT(11) DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX `idx_event_id` (`event_id`),
    INDEX `idx_state` (`state`)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_types` (
    `id`                INT(11)          NOT NULL AUTO_INCREMENT,
  `name`              VARCHAR(100)     NOT NULL DEFAULT '',
  `alias`             VARCHAR(100)     NOT NULL DEFAULT '',
  `description`       TEXT             DEFAULT NULL,
  `base_language`     CHAR(7)          NOT NULL DEFAULT '',
  `translation_languages` VARCHAR(255) DEFAULT NULL,
  `translations`      MEDIUMTEXT       DEFAULT NULL,
  `entity`            TINYINT(1)       NOT NULL DEFAULT 1 COMMENT '1=Event, 2=Category, 3=Venue, 4=Day',
    `icon`              VARCHAR(255)     DEFAULT NULL,
    `color`             VARCHAR(7)       DEFAULT NULL,
    `published`         TINYINT(1)       NOT NULL DEFAULT 1,
    `ordering`          INT(11)          NOT NULL DEFAULT 0,
    `access`            INT(10) UNSIGNED NOT NULL DEFAULT 1,
    `language`          CHAR(7)          NOT NULL DEFAULT '*',
    `checked_out`       INT(11) UNSIGNED NULL DEFAULT NULL,
    `checked_out_time`  DATETIME         NULL DEFAULT NULL,
    `created`           DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_by`        INT(11) UNSIGNED NOT NULL DEFAULT 0,
    `modified`          DATETIME         NULL DEFAULT NULL,
    `modified_by`       INT(11) UNSIGNED NOT NULL DEFAULT 0,
    `attribs`           TEXT             DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_entity`    (`entity`),
    KEY `idx_published` (`published`),
    KEY `idx_access`    (`access`),
    KEY `idx_checkout`  (`checked_out`)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_special_days` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL DEFAULT '',
  `alias` varchar(255) NOT NULL DEFAULT '',
  `day_type_id` int(11) unsigned NOT NULL DEFAULT 0,
  `day_type` varchar(100) NOT NULL DEFAULT '',
  `start_date` date NULL DEFAULT NULL,
  `end_date` date NULL DEFAULT NULL,
  `weekdays` varchar(32) NOT NULL DEFAULT '',
  `country` varchar(255) NOT NULL DEFAULT '',
  `region` varchar(100) NOT NULL DEFAULT '',
  `city` varchar(100) NOT NULL DEFAULT '',
  `description` text DEFAULT NULL,
  `article_id` int(10) unsigned NOT NULL DEFAULT 0,
  `url` varchar(2048) NOT NULL DEFAULT '',
  `show_dates` tinyint(1) NOT NULL DEFAULT 1,
  `published` tinyint(1) NOT NULL DEFAULT 1,
  `access` int(10) unsigned NOT NULL DEFAULT 1,
  `ordering` int(11) NOT NULL DEFAULT 0,
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int(11) unsigned NOT NULL DEFAULT 0,
  `modified` datetime NULL DEFAULT NULL,
  `modified_by` int(11) unsigned NOT NULL DEFAULT 0,
  `checked_out` int(11) unsigned NULL DEFAULT NULL,
  `checked_out_time` datetime NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_published_dates` (`published`, `start_date`, `end_date`),
  KEY `idx_weekdays` (`weekdays`),
  KEY `idx_day_type_id` (`day_type_id`),
  KEY `idx_day_type` (`day_type`),
  KEY `idx_article_id` (`article_id`),
  KEY `idx_access` (`access`),
  KEY `idx_location` (`country`, `region`, `city`),
  KEY `idx_checkout` (`checked_out`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `#__jem_import_profiles` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL DEFAULT '',
  `context` varchar(50) NOT NULL DEFAULT 'events',
  `source_format` varchar(20) NOT NULL DEFAULT 'csv',
  `source_signature` varchar(64) DEFAULT NULL,
  `mapping` mediumtext NOT NULL,
  `options` mediumtext DEFAULT NULL,
  `published` tinyint(1) NOT NULL DEFAULT 1,
  `access` int(10) unsigned NOT NULL DEFAULT 1,
  `ordering` int(11) NOT NULL DEFAULT 0,
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int(11) unsigned NOT NULL DEFAULT 0,
  `modified` datetime NULL DEFAULT NULL,
  `modified_by` int(11) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_context_format` (`context`, `source_format`),
  KEY `idx_published` (`published`),
  KEY `idx_access` (`access`)
) ENGINE=InnoDB;

INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES
('oldevent', '2'),
('minus', '1'),
('showtime', '1'),
('showtitle', '1'),
('showlocate', '1'),
('showcity', '1'),
('tablewidth', ''),
('datewidth', '20%'),
('datemode', '1'),
('titlewidth', '20%'),
('locationwidth', '15%'),
('citywidth', '15%'),
('formatdate', 'D, j. F Y'),
('formatShortDate', 'd.m.y'),
('formattime', 'H:i'),
('formathour', 'H'),
('timename', 'h'),
('show_date_in_title', '1'),
('showdetails', '1'),
('showlinkvenue', '1'),
('delivereventsyes', '-2'),
('datdesclimit', '1000'),
('autopubl', '-2'),
('deliverlocsyes', '-2'),
('autopublocate', '-2'),
('showcat', '1'),
('catfrowidth', '15%'),
('image_filetypes', 'jpg,gif,png,webp'),
('sizelimit', '200'),
('image_min_dimension', '64'),
('image_max_dimension', '3840'),
('imagehight', '200'),
('imagewidth', '200'),
('image_event_intro_mode', 'none'),
('image_event_intro_required', '0'),
('image_event_intro_ratio', '16_9'),
('image_event_intro_custom_ratio', '16:9'),
('image_event_full_mode', 'none'),
('image_event_full_required', '0'),
('image_event_full_ratio', '16_9'),
('image_event_full_custom_ratio', '16:9'),
('image_venue_mode', 'none'),
('image_venue_required', '0'),
('image_venue_ratio', '4_3'),
('image_venue_custom_ratio', '4:3'),
('image_category_mode', 'none'),
('image_category_required', '0'),
('image_category_ratio', '1_1'),
('image_category_custom_ratio', '1:1'),
('pdf_imageheight', '40'),
('pdf_imagewidth', '40'),
('pdf_enabled_views', 'annualcalendar,attendeeregistrations,calendar,categories,category,day,event,eventslist,eventsmap,myattendances,myevents,mytimeline,myvenues,specialdays,typeevents,typevenues,venue,venues,venueslist,venuesmap,weekcal'),
('pdf_paper_size', 'A4'),
('pdf_orientation', 'L'),
('pdf_calendar_layout', 'calendar'),
('pdf_margin_profile', 'medium'),
('pdf_margin_top', '14'),
('pdf_margin_right', '14'),
('pdf_margin_bottom', '14'),
('pdf_margin_left', '14'),
('pdf_background_color', '#ffffff'),
('pdf_include_view_text', '1'),
('pdf_show_footer', '1'),
('pdf_include_generated_stamp', '1'),
('pdf_title_font_family', 'helvetica'),
('pdf_header_font_family', 'helvetica'),
('pdf_body_font_family', 'helvetica'),
('pdf_accent_color', '#1d4ed8'),
('pdf_title_font_size', '18'),
('pdf_base_font_size', '8'),
('pdf_heading_font_size', '12'),
('pdf_event_layout', 'details'),
('pdf_list_paper_size', 'A4'),
('pdf_list_orientation', 'P'),
('pdf_map_paper_size', 'A4'),
('pdf_map_orientation', 'L'),
('pdf_event_description_mode', 'complete'),
('pdf_venue_description_mode', 'complete'),
('pdf_event_imagewidth', '40'),
('pdf_event_imageheight', '40'),
('pdf_event_image_position', 'right'),
('pdf_venue_imagewidth', '40'),
('pdf_venue_imageheight', '40'),
('pdf_venue_image_position', 'right'),
('pdf_event_show_images', '1'),
('pdf_event_include_links', '1'),
('pdf_event_include_attachments', '1'),
('pdf_event_include_registration', '1'),
('pdf_event_include_contacts', '1'),
('pdf_event_include_online_meeting', '1'),
('pdf_event_venue_mode', 'full'),
('pdf_event_include_venue_map', 'none'),
('pdf_annual_paper_size', 'A4'),
('pdf_annual_orientation', 'L'),
('pdf_annual_month_matrix', 'auto'),
('pdf_annual_vertical_align', 'top'),
('pdf_annual_show_day_types_legend', '1'),
('pdf_annual_show_categories_legend', '1'),
('pdf_annual_event_titles', 'auto'),
('pdf_annual_event_limit', '6'),
('pdf_annual_column_gap', '1'),
('pdf_annual_row_gap', '1'),
('gddisabled', '1'),
('imageenabled', '1'),
('attachmentenabled', '1'),
('frontendpublish','0'),
('catlinklist', '1'),
('showfroregistra', '2'),
('showfrounregistra', '2'),
('eventedit', '-2'),
('eventowner', '0'),
('venueedit', '-2'),
('venueowner', '0'),
('lightbox', '1'),
('meta_keywords', '[title], [a_name], [categories], [times]'),
('meta_description', 'The event titled [title] starts on [dates]!'),
('showstate', '1'),
('showeventimage', '0'),
('statewidth', '15%'),
('storeip', '0'),
('storeipmode', 'full'),
('lastupdate', '0'),
('tableeventimagewidth', '10%'),
('display_num', '10'),
('fancy_select_threshold', '10'),
('discatheader', '1'),
('showatte', '0'),
('attewidth', '10%'),
('weekdaystart', '1'),
('ical_tz', '1'),
('event_timezone_default', 'joomla'),
('attachments_path', 'media/com_jem/attachments'),
('attachments_maxsize', '1000'),
('attachments_types', 'txt,pdf,doc,docx,xls,xlsx,ppt,pptx,csv,ics,jpg,jpeg,gif,png,webp,zip,tar.gz'),
('attachments_layout', 'column'),
('attachments_icon_size', 'normal'),
('recurrence_anticipation_day', '3'),
('recurrence_anticipation_week', '12'),
('recurrence_anticipation_month', '60'),
('recurrence_anticipation_year', '180'),
('recurrence_anticipation_lastday', '60'),
('ical_max_items', '100'),
('backend_events_order', 'a.dates'),
('backend_events_direction', 'ASC'),
('defaultCountry', ''),
('defaultCurrency', 'EUR'),
('flagicons_path', 'media/com_jem/images/flags/w80-webp/'),
('csv_separator', ';'),
('csv_delimiter', '"'),
('csv_bom', '1'),
('globalattribs', '{"loglevel":"2","actionlog_enabled":"0","import_additional_blocked_tags":"","import_allow_trusted_iframes":"0","import_trusted_iframe_hosts":"","event_show_online_meeting":"1","event_online_meeting_ics":"1","event_online_meeting_ics_description":"1","event_online_meeting_default_label":"","event_details_layout":"details","event_detail_image_layout":"right","event_detail_image_header_display":"fill","event_detail_image_header_max_height":"420","event_venue_layout":"details","event_show_venue_configuration":"1","event_show_publish_state":"0","calendar_special_days_enabled":"1","calendar_special_day_types":"Weekend | #d1d5db | 0\\nPublic holiday | #e5e7eb | 0"}'),
('css', '{"css_backend_usecustom":"0","css_backend_customfile":"","css_calendar_usecustom":"0","css_calendar_customfile":"","css_geostyle_usecustom":"0","css_geostyle_customfile":"","css_googlemap_usecustom":"0","css_googlemap_customfile":"","css_jem_usecustom":"0","css_jem_customfile":"","css_print_usecustom":"0","css_print_customfile":"","css_color_bg_filter":"#ffa500","css_color_bg_h2":"","css_color_bg_jem":"","css_color_bg_table_th":"","css_color_bg_table_td":"","css_color_bg_table_tr_entry2":"","css_color_bg_table_tr_hover":"","css_color_bg_table_tr_featured":"","css_color_border_filter":"","css_color_border_h2":"","css_color_border_table_th":"","css_color_border_table_td":"","css_color_font_h2":"","css_color_font_table_th":"","css_color_font_table_td":"","css_color_font_table_td_a":""}'),
('regallowcomments', '0'),
('regallowinvitation', '0'),
('waitinglist_automatic', '1'),
('waitinglist_strategy', 'strict'),
('registration_schema_ready', '1'),
('notification_retention_days', '0'),
('notification_user_resend_limit', '2'),
('notification_user_resend_window_hours', '24'),
('notification_user_resend_cooldown_minutes', '10'),
('notification_max_attempts', '4'),
('reminders_enabled', '0'),
('reminder_all_day_time', '09:00'),
('notification_retry_delays_minutes', '10,30,120'),
('notification_schema_ready', '1'),
('pricing_schema_ready', '1'),
('operating_profile', 'essential'),
('operating_profile_configured', '0'),
('layoutstyle', '1'),
('useiconfont', '1'),
('flyer', '0'),
('categories_order', '2'),
('access_level_locked_events', '[\"1\"]'),
('access_level_locked_venues', '[\"1\"]'),
('access_level_locked_categories', '[\"1\"]'),
('defaultCategory', '0'),
('defaultVenue', '0'),
('event_show_venue', '1'),
('event_custom_fields_position', 'details'),
('global_venue_custom_fields_position', 'details'),
('event_show_registration', '1'),
('event_show_registration_counters', '1');

INSERT IGNORE INTO `#__jem_countries` (`id`, `continent`, `iso2`, `iso3`, `un`, `name`) VALUES
(1, 'AS', 'AF', 'AFG', 4, 'Afghanistan'),
(2, 'EU', 'AX', 'ALA', 248, 'Aland Islands'),
(3, 'EU', 'AL', 'ALB', 8, 'Albania'),
(4, 'AF', 'DZ', 'DZA', 12, 'Algeria'),
(5, 'OC', 'AS', 'ASM', 16, 'American Samoa'),
(6, 'EU', 'AD', 'AND', 20, 'Andorra'),
(7, 'AF', 'AO', 'AGO', 24, 'Angola'),
(8, 'NA', 'AI', 'AIA', 660, 'Anguilla'),
(9, 'AN', 'AQ', 'ATA', 10, 'Antarctica'),
(10, 'NA', 'AG', 'ATG', 28, 'Antigua and Barbuda'),
(11, 'SA', 'AR', 'ARG', 32, 'Argentina'),
(12, 'AS', 'AM', 'ARM', 51, 'Armenia'),
(13, 'NA', 'AW', 'ABW', 533, 'Aruba'),
(14, 'OC', 'AU', 'AUS', 36, 'Australia'),
(15, 'EU', 'AT', 'AUT', 40, 'Austria'),
(16, 'AS', 'AZ', 'AZE', 31, 'Azerbaijan'),
(17, 'NA', 'BS', 'BHS', 44, 'Bahamas'),
(18, 'AS', 'BH', 'BHR', 48, 'Bahrain'),
(19, 'AS', 'BD', 'BGD', 50, 'Bangladesh'),
(20, 'NA', 'BB', 'BRB', 52, 'Barbados'),
(21, 'EU', 'BY', 'BLR', 112, 'Belarus'),
(22, 'EU', 'BE', 'BEL', 56, 'Belgium'),
(23, 'NA', 'BZ', 'BLZ', 84, 'Belize'),
(24, 'AF', 'BJ', 'BEN', 204, 'Benin'),
(25, 'NA', 'BM', 'BMU', 60, 'Bermuda'),
(26, 'AS', 'BT', 'BTN', 64, 'Bhutan'),
(27, 'SA', 'BO', 'BOL', 68, 'Bolivia'),
(28, 'EU', 'BA', 'BIH', 70, 'Bosnia and Herzegovina'),
(29, 'AF', 'BW', 'BWA', 72, 'Botswana'),
(30, 'AN', 'BV', 'BVT', 74, 'Bouvet Island'),
(31, 'SA', 'BR', 'BRA', 76, 'Brazil'),
(32, 'AS', 'IO', 'IOT', 86, 'British Indian Ocean Territory'),
(33, 'NA', 'VG', 'VGB', 92, 'Virgin Islands (British), British Virgin Islands'),
(34, 'AS', 'BN', 'BRN', 96, 'Brunei Darussalam'),
(35, 'EU', 'BG', 'BGR', 100, 'Bulgaria'),
(36, 'AF', 'BF', 'BFA', 854, 'Burkina Faso'),
(37, 'AF', 'BI', 'BDI', 108, 'Burundi'),
(38, 'AS', 'KH', 'KHM', 116, 'Cambodia'),
(39, 'AF', 'CM', 'CMR', 120, 'Cameroon'),
(40, 'NA', 'CA', 'CAN', 124, 'Canada'),
(41, 'AF', 'CV', 'CPV', 132, 'Cape Verde'),
(42, 'NA', 'KY', 'CYM', 136, 'Cayman Islands'),
(43, 'AF', 'CF', 'CAF', 140, 'Central African Republic'),
(44, 'AF', 'TD', 'TCD', 148, 'Chad'),
(45, 'SA', 'CL', 'CHL', 152, 'Chile'),
(46, 'AS', 'CN', 'CHN', 156, 'China'),
(47, 'AS', 'CX', 'CXR', 162, 'Christmas Island'),
(48, 'AS', 'CC', 'CCK', 166, 'Cocos (Keeling) Islands'),
(49, 'SA', 'CO', 'COL', 170, 'Colombia'),
(50, 'AF', 'KM', 'COM', 174, 'Comoros (the)'),
(51, 'AF', 'CD', 'COD', 180, 'Congo (the Democratic Republic of)'),
(52, 'AF', 'CG', 'COG', 178, 'Congo'),
(53, 'OC', 'CK', 'COK', 184, 'Cook Islands '),
(54, 'NA', 'CR', 'CRI', 188, 'Costa Rica'),
(55, 'AF', 'CI', 'CIV', 384, 'Cote d\'Ivoire (Ivory Coast), Republic of'),
(56, 'EU', 'HR', 'HRV', 191, 'Croatia'),
(57, 'NA', 'CU', 'CUB', 192, 'Cuba'),
(58, 'AS', 'CY', 'CYP', 196, 'Cyprus'),
(59, 'EU', 'CZ', 'CZE', 203, 'Czechia'),
(60, 'EU', 'DK', 'DNK', 208, 'Denmark'),
(61, 'AF', 'DJ', 'DJI', 262, 'Djibouti'),
(62, 'NA', 'DM', 'DMA', 212, 'Dominica'),
(63, 'NA', 'DO', 'DOM', 214, 'Dominican Republic'),
(64, 'SA', 'EC', 'ECU', 218, 'Ecuador'),
(65, 'AF', 'EG', 'EGY', 818, 'Egypt'),
(66, 'NA', 'SV', 'SLV', 222, 'El Salvador'),
(67, 'AF', 'GQ', 'GNQ', 226, 'Equatorial Guinea'),
(68, 'AF', 'ER', 'ERI', 232, 'Eritrea'),
(69, 'EU', 'EE', 'EST', 233, 'Estonia'),
(70, 'AF', 'ET', 'ETH', 231, 'Ethiopia'),
(71, 'EU', 'FO', 'FRO', 234, 'Faroe Islands'),
(72, 'SA', 'FK', 'FLK', 238, 'Falkland Islands [Malvinas]'),
(73, 'OC', 'FJ', 'FJI', 242, 'Fiji'),
(74, 'EU', 'FI', 'FIN', 246, 'Finland'),
(75, 'EU', 'FR', 'FRA', 250, 'France'),
(76, 'SA', 'GF', 'GUF', 254, 'French Guiana'),
(77, 'OC', 'PF', 'PYF', 258, 'French Polynesia'),
(78, 'AN', 'TF', 'ATF', 260, 'French Southern Territories'),
(79, 'AF', 'GA', 'GAB', 266, 'Gabon'),
(80, 'AF', 'GM', 'GMB', 270, 'Gambia'),
(81, 'AS', 'GE', 'GEO', 268, 'Georgia'),
(82, 'EU', 'DE', 'DEU', 276, 'Germany'),
(83, 'AF', 'GH', 'GHA', 288, 'Ghana'),
(84, 'EU', 'GI', 'GIB', 292, 'Gibraltar'),
(85, 'EU', 'GR', 'GRC', 300, 'Greece'),
(86, 'NA', 'GL', 'GRL', 304, 'Greenland'),
(87, 'NA', 'GD', 'GRD', 308, 'Grenada'),
(88, 'NA', 'GP', 'GLP', 312, 'Guadeloupe'),
(89, 'OC', 'GU', 'GUM', 316, 'Guam'),
(90, 'NA', 'GT', 'GTM', 320, 'Guatemala'),
(91, 'EU', 'GG', 'GGY', 831, 'Guernsey'),
(92, 'AF', 'GN', 'GIN', 324, 'Guinea'),
(93, 'AF', 'GW', 'GNB', 624, 'Guinea-Bissau'),
(94, 'SA', 'GY', 'GUY', 328, 'Guyana'),
(95, 'NA', 'HT', 'HTI', 332, 'Haiti'),
(96, 'AN', 'HM', 'HMD', 334, 'Heard Island and McDonald Islands'),
(97, 'EU', 'VA', 'VAT', 336, 'Vatican City'),
(98, 'NA', 'HN', 'HND', 340, 'Honduras'),
(99, 'AS', 'HK', 'HKG', 344, 'Hong Kong'),
(100, 'EU', 'HU', 'HUN', 348, 'Hungary'),
(101, 'EU', 'IS', 'ISL', 352, 'Iceland'),
(102, 'AS', 'IN', 'IND', 356, 'India'),
(103, 'AS', 'ID', 'IDN', 360, 'Indonesia'),
(104, 'AS', 'IR', 'IRN', 364, 'Iran'),
(105, 'AS', 'IQ', 'IRQ', 368, 'Iraq'),
(106, 'EU', 'IE', 'IRL', 372, 'Ireland'),
(107, 'EU', 'IM', 'IMN', 833, 'Isle of Man'),
(108, 'AS', 'IL', 'ISR', 376, 'Israel'),
(109, 'EU', 'IT', 'ITA', 380, 'Italy'),
(110, 'NA', 'JM', 'JAM', 388, 'Jamaica'),
(111, 'AS', 'JP', 'JPN', 392, 'Japan'),
(112, 'EU', 'JE', 'JEY', 832, 'Jersey'),
(113, 'AS', 'JO', 'JOR', 400, 'Jordan'),
(114, 'AS', 'KZ', 'KAZ', 398, 'Kazakhstan'),
(115, 'AF', 'KE', 'KEN', 404, 'Kenya'),
(116, 'OC', 'KI', 'KIR', 296, 'Kiribati'),
(117, 'AS', 'KP', 'PRK', 408, 'North Korea'),
(118, 'AS', 'KR', 'KOR', 410, 'South Korea'),
(119, 'AS', 'KW', 'KWT', 414, 'Kuwait'),
(120, 'AS', 'KG', 'KGZ', 417, 'Kyrgyzstan'),
(121, 'AS', 'LA', 'LAO', 418, 'Laos'),
(122, 'EU', 'LV', 'LVA', 428, 'Latvia'),
(123, 'AS', 'LB', 'LBN', 422, 'Lebanon'),
(124, 'AF', 'LS', 'LSO', 426, 'Lesotho'),
(125, 'AF', 'LR', 'LBR', 430, 'Liberia'),
(126, 'AF', 'LY', 'LBY', 434, 'Libya'),
(127, 'EU', 'LI', 'LIE', 438, 'Liechtenstein'),
(128, 'EU', 'LT', 'LTU', 440, 'Lithuania'),
(129, 'EU', 'LU', 'LUX', 442, 'Luxembourg'),
(130, 'AS', 'MO', 'MAC', 446, 'Macao'),
(131, 'EU', 'MK', 'MKD', 807, 'Macedonia'),
(132, 'AF', 'MG', 'MDG', 450, 'Madagascar'),
(133, 'AF', 'MW', 'MWI', 454, 'Malawi'),
(134, 'AS', 'MY', 'MYS', 458, 'Malaysia'),
(135, 'AS', 'MV', 'MDV', 462, 'Maldives'),
(136, 'AF', 'ML', 'MLI', 466, 'Mali'),
(137, 'EU', 'MT', 'MLT', 470, 'Malta'),
(138, 'OC', 'MH', 'MHL', 584, 'Marshall Islands'),
(139, 'NA', 'MQ', 'MTQ', 474, 'Martinique'),
(140, 'AF', 'MR', 'MRT', 478, 'Mauritania'),
(141, 'AF', 'MU', 'MUS', 480, 'Mauritius'),
(142, 'AF', 'YT', 'MYT', 175, 'Mayotte'),
(143, 'NA', 'MX', 'MEX', 484, 'Mexico'),
(144, 'OC', 'FM', 'FSM', 583, 'Micronesia'),
(145, 'EU', 'MD', 'MDA', 498, 'Moldova'),
(146, 'EU', 'MC', 'MCO', 492, 'Monaco'),
(147, 'AS', 'MN', 'MNG', 496, 'Mongolia'),
(148, 'EU', 'ME', 'MNE', 499, 'Montenegro'),
(149, 'NA', 'MS', 'MSR', 500, 'Montserrat'),
(150, 'AF', 'MA', 'MAR', 504, 'Morocco'),
(151, 'AF', 'MZ', 'MOZ', 508, 'Mozambique'),
(152, 'AS', 'MM', 'MMR', 104, 'Myanmar (Burma)'),
(153, 'AF', 'NA', 'NAM', 516, 'Namibia'),
(154, 'OC', 'NR', 'NRU', 520, 'Nauru'),
(155, 'AS', 'NP', 'NPL', 524, 'Nepal'),
(157, 'EU', 'NL', 'NLD', 528, 'Netherlands'),
(158, 'OC', 'NC', 'NCL', 540, 'New Caledonia'),
(159, 'OC', 'NZ', 'NZL', 554, 'New Zealand'),
(160, 'NA', 'NI', 'NIC', 558, 'Nicaragua'),
(161, 'AF', 'NE', 'NER', 562, 'Niger'),
(162, 'AF', 'NG', 'NGA', 566, 'Nigeria'),
(163, 'OC', 'NU', 'NIU', 570, 'Niue'),
(164, 'OC', 'NF', 'NFK', 574, 'Norfolk Island'),
(165, 'OC', 'MP', 'MNP', 580, 'Northern Mariana Islands'),
(166, 'EU', 'NO', 'NOR', 578, 'Norway'),
(167, 'AS', 'OM', 'OMN', 512, 'Oman'),
(168, 'AS', 'PK', 'PAK', 586, 'Pakistan'),
(169, 'OC', 'PW', 'PLW', 585, 'Palau'),
(170, 'AS', 'PS', 'PSE', 275, 'Palestine'),
(171, 'NA', 'PA', 'PAN', 591, 'Panama'),
(172, 'OC', 'PG', 'PNG', 598, 'Papua New Guinea'),
(173, 'SA', 'PY', 'PRY', 600, 'Paraguay'),
(174, 'SA', 'PE', 'PER', 604, 'Peru'),
(175, 'AS', 'PH', 'PHL', 608, 'Philippines'),
(176, 'OC', 'PN', 'PCN', 612, 'Pitcairn'),
(177, 'EU', 'PL', 'POL', 616, 'Poland'),
(178, 'EU', 'PT', 'PRT', 620, 'Portugal'),
(179, 'NA', 'PR', 'PRI', 630, 'Puerto Rico'),
(180, 'AS', 'QA', 'QAT', 634, 'Qatar'),
(181, 'AF', 'RE', 'REU', 638, 'Reunion'),
(182, 'EU', 'RO', 'ROU', 642, 'Romania'),
(183, 'EU', 'RU', 'RUS', 643, 'Russia'),
(184, 'AF', 'RW', 'RWA', 646, 'Rwanda'),
(185, 'NA', 'BL', 'BLM', 652, 'Saint Barthelemy'),
(186, 'AF', 'SH', 'SHN', 654, 'Saint Helena, Ascension and Tristan da Cunha'),
(187, 'NA', 'KN', 'KNA', 659, 'Saint Kitts and Nevis'),
(188, 'NA', 'LC', 'LCA', 662, 'Saint Lucia'),
(189, 'NA', 'MF', 'MAF', 663, 'Saint Martin'),
(190, 'NA', 'PM', 'SPM', 666, 'Saint Pierre and Miquelon'),
(191, 'NA', 'VC', 'VCT', 670, 'Saint Vincent and the Grenadines'),
(192, 'OC', 'WS', 'WSM', 882, 'Samoa'),
(193, 'EU', 'SM', 'SMR', 674, 'San Marino'),
(194, 'AF', 'ST', 'STP', 678, 'Sao Tome and Principe'),
(195, 'AS', 'SA', 'SAU', 682, 'Saudi Arabia'),
(196, 'AF', 'SN', 'SEN', 686, 'Senegal'),
(197, 'EU', 'RS', 'SRB', 688, 'Serbia'),
(198, 'AF', 'SC', 'SYC', 690, 'Seychelles'),
(199, 'AF', 'SL', 'SLE', 694, 'Sierra Leone'),
(200, 'AS', 'SG', 'SGP', 702, 'Singapore'),
(201, 'EU', 'SK', 'SVK', 703, 'Slovakia'),
(202, 'EU', 'SI', 'SVN', 705, 'Slovenia'),
(203, 'OC', 'SB', 'SLB', 90, 'Solomon Islands'),
(204, 'AF', 'SO', 'SOM', 706, 'Somalia'),
(205, 'AF', 'ZA', 'ZAF', 710, 'South Africa'),
(206, 'AN', 'GS', 'SGS', 239, 'South Georgia and the South Sandwich Islands'),
(207, 'EU', 'ES', 'ESP', 724, 'Spain'),
(208, 'AS', 'LK', 'LKA', 144, 'Sri Lanka'),
(209, 'AF', 'SD', 'SDN', 736, 'Sudan'),
(210, 'SA', 'SR', 'SUR', 740, 'Suriname'),
(211, 'EU', 'SJ', 'SJM', 744, 'Svalbard and Jan Mayen'),
(212, 'AF', 'SZ', 'SWZ', 748, 'Swaziland'),
(213, 'EU', 'SE', 'SWE', 752, 'Sweden'),
(214, 'EU', 'CH', 'CHE', 756, 'Switzerland'),
(215, 'AS', 'SY', 'SYR', 760, 'Syria'),
(216, 'AS', 'TW', 'TWN', 158, 'Taiwan'),
(217, 'AS', 'TJ', 'TJK', 762, 'Tajikistan'),
(218, 'AF', 'TZ', 'TZA', 834, 'Tanzania'),
(219, 'AS', 'TH', 'THA', 764, 'Thailand'),
(220, 'AS', 'TL', 'TLS', 626, 'Timor-Leste'),
(221, 'AF', 'TG', 'TGO', 768, 'Togo'),
(222, 'OC', 'TK', 'TKL', 772, 'Tokelau'),
(223, 'OC', 'TO', 'TON', 776, 'Tonga'),
(224, 'NA', 'TT', 'TTO', 780, 'Trinidad and Tobago'),
(225, 'AF', 'TN', 'TUN', 788, 'Tunisia'),
(226, 'AS', 'TR', 'TUR', 792, 'Turkey'),
(227, 'AS', 'TM', 'TKM', 795, 'Turkmenistan'),
(228, 'NA', 'TC', 'TCA', 796, 'Turks and Caicos Islands'),
(229, 'OC', 'TV', 'TUV', 798, 'Tuvalu'),
(230, 'AF', 'UG', 'UGA', 800, 'Uganda'),
(231, 'EU', 'UA', 'UKR', 804, 'Ukraine'),
(232, 'AS', 'AE', 'ARE', 784, 'United Arab Emirates'),
(233, 'EU', 'GB', 'GBR', 826, 'United Kingdom'),
(234, 'NA', 'US', 'USA', 840, 'United States'),
(235, 'OC', 'UM', 'UMI', 581, 'United States Minor Outlying Islands'),
(236, 'NA', 'VI', 'VIR', 850, 'Virgin Islands (US)'),
(237, 'SA', 'UY', 'URY', 858, 'Uruguay'),
(238, 'AS', 'UZ', 'UZB', 860, 'Uzbekistan'),
(239, 'OC', 'VU', 'VUT', 548, 'Vanuatu'),
(240, 'SA', 'VE', 'VEN', 862, 'Venezuela'),
(241, 'AS', 'VN', 'VNM', 704, 'Vietnam'),
(242, 'OC', 'WF', 'WLF', 876, 'Wallis and Futuna'),
(243, 'AF', 'EH', 'ESH', 732, 'Western Sahara'),
(244, 'AS', 'YE', 'YEM', 887, 'Yemen'),
(245, 'AF', 'ZM', 'ZMB', 894, 'Zambia'),
(246, 'AF', 'ZW', 'ZWE', 716, 'Zimbabwe'),
(247, 'NA', 'BQ', 'BES', 535, 'Bonaire, Sint Eustatius and Saba'),
(248, 'NA', 'CW', 'CUW', 531, 'Curacao'),
(249, 'NA', 'SX', 'SXM', 534, 'Sint Maarten'),
(250, 'AF', 'SS', 'SSD', 728, 'South Sudan'),
(251, 'EU', 'XK', 'XKX', 688, 'Kosovo');

INSERT IGNORE INTO `#__jem_categories` (`id`, `parent_id`, `lft`, `rgt`, `level`, `catname`, `alias`, `access`, `published`, `created_time`, `path` ) VALUES
(1, 0, 0, 3, 0, 'root', 'root', 1, 1, NOW(), NULL),
(2, 1, 1, 2, 1, 'Uncategorised', 'uncategorised', 1, 1, NOW(), 'uncategorised');

INSERT IGNORE INTO `#__jem_types` (`name`, `alias`, `entity`, `color`, `published`, `ordering`, `access`, `language`, `created`, `attribs`) VALUES
('Weekend', 'weekend', 4, '#d1d5db', 1, 1, 1, '*', NOW(), '{"block_events":0}'),
('Public holiday', 'public-holiday', 4, '#e5e7eb', 1, 2, 1, '*', NOW(), '{"block_events":0}');

INSERT IGNORE INTO `#__jem_special_days` (`id`, `title`, `alias`, `day_type_id`, `day_type`, `start_date`, `end_date`, `weekdays`, `description`, `show_dates`, `published`, `access`, `ordering`, `created`) VALUES
(1, 'Saturday and Sunday', 'weekend', (SELECT `id` FROM `#__jem_types` WHERE `alias` = 'weekend' AND `entity` = 4 ORDER BY `id` ASC LIMIT 1), 'Weekend', '2026-01-01', '2030-12-31', '0,6', 'Regular weekend days', 0, 1, 1, 1, NOW());
