-- delete values

-- new values
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_imageheight', '40');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_imagewidth', '40');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_enabled_views', 'annualcalendar,attendeeregistrations,calendar,categories,category,day,event,eventslist,eventsmap,myattendances,myevents,mytimeline,myvenues,specialdays,typeevents,typevenues,venue,venues,venueslist,venuesmap,weekcal');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_paper_size', 'A4');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_orientation', 'L');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_calendar_layout', 'calendar');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_margin_profile', 'medium');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_margin_top', '14');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_margin_right', '14');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_margin_bottom', '14');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_margin_left', '14');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_background_color', '#ffffff');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_include_view_text', '1');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_show_footer', '1');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_include_generated_stamp', '1');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_title_font_family', 'helvetica');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_header_font_family', 'helvetica');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_body_font_family', 'helvetica');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_accent_color', '#1d4ed8');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_base_font_size', '8');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_heading_font_size', '12');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_event_layout', 'details');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_list_paper_size', 'A4');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_list_orientation', 'P');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_map_paper_size', 'A4');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_map_orientation', 'L');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_event_description_mode', 'complete');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_venue_description_mode', 'complete');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_event_imagewidth', '40');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_event_imageheight', '40');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_event_image_position', 'right');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_venue_imagewidth', '40');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_venue_imageheight', '40');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_venue_image_position', 'right');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_event_show_images', '1');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_event_include_links', '1');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_event_include_attachments', '1');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_event_include_registration', '1');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_event_include_contacts', '1');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_event_include_online_meeting', '1');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_event_venue_mode', 'full');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_event_include_venue_map', 'none');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_annual_paper_size', 'A4');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_annual_orientation', 'L');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_annual_month_matrix', 'auto');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_annual_vertical_align', 'top');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_annual_show_day_types_legend', '1');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_annual_show_categories_legend', '1');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_annual_event_titles', 'auto');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_annual_event_limit', '6');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_annual_column_gap', '1');
INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('pdf_annual_row_gap', '1');

-- change values
UPDATE `#__jem_config` SET `value` = JSON_INSERT(`value`, '$.actionlog_enabled', '0') WHERE `keyname` = 'globalattribs' AND JSON_EXTRACT(`value`, '$.actionlog_enabled') IS NULL;
UPDATE `#__jem_config` SET `value` = JSON_INSERT(`value`, '$.event_detail_image_layout', 'right', '$.event_detail_image_header_display', 'fill', '$.event_detail_image_header_max_height', '420') WHERE `keyname` = 'globalattribs' AND JSON_EXTRACT(`value`, '$.event_detail_image_layout') IS NULL;
UPDATE `#__jem_config` SET `value` = JSON_INSERT(`value`, '$.event_detail_image_header_display', 'fill', '$.event_detail_image_header_max_height', '420') WHERE `keyname` = 'globalattribs' AND JSON_EXTRACT(`value`, '$.event_detail_image_header_display') IS NULL;
UPDATE `#__jem_config` SET `value` = JSON_INSERT(`value`, '$.calendar_special_days_enabled', '1', '$.calendar_special_day_types', 'Weekend | #d1d5db | 0\nPublic holiday | #e5e7eb | 0') WHERE `keyname` = 'globalattribs';
UPDATE `#__jem_special_days` SET `title` = 'Saturday and Sunday', `description` = 'Regular weekend days' WHERE `title` = 'Weekend' AND `day_type` = 'Weekend' AND (`description` IS NULL OR `description` = '');
UPDATE `#__jem_special_days` SET `show_dates` = 0 WHERE `alias` = 'weekend' AND `day_type` = 'Weekend' AND `weekdays` IN ('0,6', '6,0');
ALTER TABLE `#__jem_types` MODIFY `entity` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1=Event, 2=Category, 3=Venue, 4=Day';
INSERT IGNORE INTO `#__jem_types` (`name`, `alias`, `entity`, `color`, `published`, `ordering`, `access`, `language`, `created`, `attribs`) VALUES ('Weekend', 'weekend', 4, '#d1d5db', 1, 1, 1, '*', CURRENT_TIMESTAMP, '{"block_events":0}'), ('Public holiday', 'public-holiday', 4, '#e5e7eb', 1, 2, 1, '*', CURRENT_TIMESTAMP, '{"block_events":0}');
UPDATE `#__jem_special_days` AS sd INNER JOIN `#__jem_types` AS t ON t.entity = 4 AND t.name = sd.day_type SET sd.day_type_id = t.id WHERE sd.day_type_id = 0;
UPDATE `#__jem_venues` SET `attribs` = '{}' WHERE `attribs` IS NULL OR `attribs` = '' OR `attribs` = '""' OR `attribs` = "''" OR NOT JSON_VALID(`attribs`);
UPDATE `#__jem_events` SET `attribs` = '{}' WHERE `attribs` IS NULL OR `attribs` = '' OR `attribs` = '""' OR `attribs` = "''" OR NOT JSON_VALID(`attribs`);
UPDATE `#__jem_categories` SET `metadata` = '{}' WHERE `metadata` IS NULL OR `metadata` = '' OR `metadata` = '""' OR `metadata` = "''" OR NOT JSON_VALID(`metadata`);
UPDATE `#__jem_categories` SET `path` = NULL WHERE `id` = 1 AND `catname` = 'root' AND `path` IS NOT NULL;
UPDATE `#__jem_config` SET `value` = 'annualcalendar,attendeeregistrations,calendar,categories,category,day,event,eventslist,eventsmap,myattendances,myevents,mytimeline,myvenues,specialdays,typeevents,typevenues,venue,venues,venueslist,venuesmap,weekcal' WHERE `keyname` = 'pdf_enabled_views' AND `value` = 'event,annualcalendar';
UPDATE `#__jem_config` SET `value` = CONCAT(`value`, ',categories') WHERE `keyname` = 'pdf_enabled_views' AND FIND_IN_SET('categories', `value`) = 0;
UPDATE `#__jem_config` SET `value` = CONCAT(`value`, ',typevenues') WHERE `keyname` = 'pdf_enabled_views' AND FIND_IN_SET('typevenues', `value`) = 0;
UPDATE `#__jem_config` SET `value` = CONCAT(`value`, ',venues') WHERE `keyname` = 'pdf_enabled_views' AND FIND_IN_SET('venues', `value`) = 0;

-- update values
UPDATE `#__jem_events` SET `publish_up` = `created` WHERE `publish_up` IS NULL AND `created` IS NOT NULL;
UPDATE `#__jem_events` SET `language` = '*' WHERE `language` = '' OR `language` IS NULL;
UPDATE `#__jem_categories` SET `language` = '*' WHERE `language` = '' OR `language` IS NULL;
UPDATE `#__jem_venues` SET `language` = '*' WHERE `language` = '' OR `language` IS NULL;
