-- JEM 5.1.0: stable registration identity and append-only history.
-- PHP postflight performs the idempotent reference and baseline-history
-- backfill before registration writes are enabled.

ALTER TABLE `#__jem_register` ADD COLUMN `reference` VARCHAR(28) CHARACTER SET ascii COLLATE ascii_bin NULL DEFAULT NULL AFTER `comment` /** CAN FAIL **/;
ALTER TABLE `#__jem_register` ADD COLUMN `created` DATETIME NULL DEFAULT NULL AFTER `reference` /** CAN FAIL **/;
ALTER TABLE `#__jem_register` ADD COLUMN `modified` DATETIME NULL DEFAULT NULL AFTER `created` /** CAN FAIL **/;
ALTER TABLE `#__jem_register` ADD COLUMN `revision` INT(10) UNSIGNED NOT NULL DEFAULT '1' AFTER `modified` /** CAN FAIL **/;

CREATE TABLE IF NOT EXISTS `#__jem_registration_history` (`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT, `operation_reference` VARCHAR(28) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `registration_id` INT(11) UNSIGNED NOT NULL, `registration_reference` VARCHAR(28) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `revision` INT(10) UNSIGNED NOT NULL, `event_id` INT(11) UNSIGNED NOT NULL DEFAULT '0', `event_title` VARCHAR(255) NOT NULL DEFAULT '', `action` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `old_status` TINYINT(3) NULL DEFAULT NULL, `new_status` TINYINT(3) NULL DEFAULT NULL, `old_places` INT(11) NULL DEFAULT NULL, `new_places` INT(11) NULL DEFAULT NULL, `old_user_id` INT(11) NULL DEFAULT NULL, `new_user_id` INT(11) NULL DEFAULT NULL, `actor_user_id` INT(11) UNSIGNED NOT NULL DEFAULT '0', `source` VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '', `reason_code` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL DEFAULT NULL, `forced` TINYINT(1) NOT NULL DEFAULT '0', `changed_fields` TEXT NULL DEFAULT NULL, `occurred` DATETIME NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `idx_history_registration_revision` (`registration_id`,`revision`), UNIQUE KEY `idx_history_operation_registration` (`operation_reference`,`registration_id`), KEY `idx_history_reference_occurred` (`registration_reference`,`occurred`), KEY `idx_history_operation` (`operation_reference`), KEY `idx_history_event_occurred` (`event_id`,`occurred`), KEY `idx_history_actor_occurred` (`actor_user_id`,`occurred`), KEY `idx_history_action_occurred` (`action`,`occurred`), KEY `idx_history_source_occurred` (`source`,`occurred`), KEY `idx_history_status_occurred` (`new_status`,`occurred`), KEY `idx_history_occurred` (`occurred`)) ENGINE=InnoDB;

INSERT IGNORE INTO `#__jem_config` (`keyname`, `value`) VALUES ('registration_schema_ready', '0');
